version: '3.4'

services:
  identitydb:
    image: mongo

  userInfodb:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  mangacatalog.api:
    image: ${DOCKER_REGISTRY-}mangacatalogapi
    build:
      context: .
      dockerfile: Services/MangaCatalog/MangaCatalog.API/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  userinfo.api:
    image: ${DOCKER_REGISTRY-}userinfoapi
    build:
      context: .
      dockerfile: Services/UserInfo/UserInfo.API/Dockerfile

  mangacatalog.grpc:
    image: ${DOCKER_REGISTRY-}mangacataloggrpc
    build:
      context: .
      dockerfile: Services/MangaCatalog/MangaCatalog.GRPC/Dockerfile

  userinfo.grpc:
    image: ${DOCKER_REGISTRY-}userinfogrpc
    build:
      context: .
      dockerfile: Services/UserInfo/UserInfo.GRPC/Dockerfile

volumes:
  mongo_data:


