version: '3.4'

services:
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  userInfodb:
    container_name: userInfodb
    restart: always
    ports:
      - "6379:6379"
    

  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://identitydb:27017"
    depends_on:
    - identitydb
    ports:
      - "4000:80"

  userinfo.api:
    container_name: userinfo.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=userInfodb:6379"
    depends_on:
      - userInfodb
    ports:
      - "8001:80"
